import MonthlyChart from "@/components/MonthlyChart";
import { money } from "@/lib/format";
import { getSession } from "@/lib/session";
import { getSummary } from "@/lib/summary";

export const metadata = { title: "Analytics | Chremio" };

export default async function AnalyticsPage() {
  const session = await getSession();
    if (!session) return null;

      const s = await getSummary(session.userId);

        const totalIncome = s.monthly.reduce((sum, m) => sum + m.income, 0);
          const totalExpense = s.monthly.reduce((sum, m) => sum + m.expense, 0);
            const net = totalIncome - totalExpense;
              const savingsRate =
                  totalIncome > 0 ? Math.round((net / totalIncome) * 100) : null;
                    const avgSpend = totalExpense / s.monthly.length;

                      const monthTotal = s.byCategory.reduce((sum, c) => sum + c.total, 0);
                        const top = s.byCategory[0];
                          const monthName = new Date().toLocaleDateString("en-GB", { month: "long" });

                            const card = "min-w-0 rounded-xl border border-line bg-surface p-4 sm:p-5";
                              const value = "mt-1 break-words font-heading text-lg font-semibold sm:text-xl";

                                return (
                                    <div>
                                          <h1 className="font-heading text-2xl font-semibold text-fg">Analytics</h1>
                                                <p className="text-sm text-muted">
                                                        Understand your spending. Make better decisions.
                                                              </p>

                                                                    <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
                                                                            <div className={card}>
                                                                                      <p className="text-sm text-muted">Income (6 months)</p>
                                                                                                <p className={`${value} text-evergreen`}>{money.format(totalIncome)}</p>
                                                                                                        </div>
                                                                                                                <div className={card}>
                                                                                                                          <p className="text-sm text-muted">Spending (6 months)</p>
                                                                                                                                    <p className={`${value} text-danger`}>{money.format(totalExpense)}</p>
                                                                                                                                            </div>
                                                                                                                                                    <div className={card}>
                                                                                                                                                              <p className="text-sm text-muted">Net savings</p>
                                                                                                                                                                        <p className={`${value} text-fg`}>{money.format(net)}</p>
                                                                                                                                                                                  {savingsRate !== null && (
                                                                                                                                                                                              <p className="mt-1 text-xs text-muted">{savingsRate}% of income</p>
                                                                                                                                                                                                        )}
                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                        <div className={card}>
                                                                                                                                                                                                                                  <p className="text-sm text-muted">Average monthly spending</p>
                                                                                                                                                                                                                                            <p className={`${value} text-fg`}>{money.format(avgSpend)}</p>
                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                <section className="mt-6 min-w-0 rounded-xl border border-line bg-surface p-5">
                                                                                                                                                                                                                                                                        <h2 className="font-heading text-lg font-semibold text-fg">
                                                                                                                                                                                                                                                                                  Income vs spending
                                                                                                                                                                                                                                                                                          </h2>
                                                                                                                                                                                                                                                                                                  <p className="mb-4 text-sm text-muted">Last 6 months</p>
                                                                                                                                                                                                                                                                                                          <MonthlyChart data={s.monthly} />
                                                                                                                                                                                                                                                                                                                </section>

                                                                                                                                                                                                                                                                                                                      <section className="mt-6 rounded-xl border border-line bg-surface p-5">
                                                                                                                                                                                                                                                                                                                              <h2 className="font-heading text-lg font-semibold text-fg">
                                                                                                                                                                                                                                                                                                                                        Where your money went in {monthName}
                                                                                                                                                                                                                                                                                                                                                </h2>

                                                                                                                                                                                                                                                                                                                                                        {s.byCategory.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                  <p className="py-8 text-center text-sm text-muted">
                                                                                                                                                                                                                                                                                                                                                                              No spending recorded this month yet.
                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                ) : (
                                                                                                                                                                                                                                                                                                                                                                                                          <>
                                                                                                                                                                                                                                                                                                                                                                                                                      {top && (
                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="mt-1 text-sm text-muted">
                                                                                                                                                                                                                                                                                                                                                                                                                                                    Highest spending:{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <strong className="text-fg">{top.category}</strong> (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {Math.round((top.total / monthTotal) * 100)}% of this
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    month&apos;s spending)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <ul className="mt-4 space-y-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {s.byCategory.map((c) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const pct = Math.round((c.total / monthTotal) * 100);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <li key={c.category}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex items-center justify-between gap-3 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-fg">{c.category}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="shrink-0 text-muted">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {money.format(c.total)} &middot; {pct}%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="mt-1.5 h-2 rounded-full bg-surface-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="h-2 rounded-full bg-evergreen"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{ width: `${pct}%` }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }