import Link from "next/link";
import SpendingByCategory from "@/components/SpendingByCategory";
import { formatDate, money } from "@/lib/format";
import { getSession } from "@/lib/session";
import { getSummary } from "@/lib/summary";

export const metadata = { title: "Dashboard | Chremio" };

export default async function DashboardPage() {
  const session = await getSession();
    if (!session) return null;

      const summary = await getSummary(session.userId);
        const firstName = session.name.split(" ")[0];
          const monthLabel = new Date().toLocaleDateString("en-GB", {
              month: "long",
                  year: "numeric",
                    });

                      return (
                          <div>
                                <div className="flex flex-wrap items-center justify-between gap-3">
                                        <div>
                                                  <h1 className="font-heading text-2xl font-semibold text-fg">
                                                              Welcome back, {firstName}
                                                                        </h1>
                                                                                  <p className="text-sm text-muted">
                                                                                              Here&apos;s your money at a glance.
                                                                                                        </p>
                                                                                                                </div>
                                                                                                                        <Link
                                                                                                                                  href="/transactions"
                                                                                                                                            className="rounded-lg bg-evergreen px-4 py-2.5 text-sm font-semibold text-canvas transition hover:bg-mint"
                                                                                                                                                    >
                                                                                                                                                              + Add transaction
                                                                                                                                                                      </Link>
                                                                                                                                                                            </div>

                                                                                                                                                                                  <div className="mt-6 grid gap-3 sm:grid-cols-3">
                                                                                                                                                                                          <div className="min-w-0 rounded-xl border border-evergreen/40 bg-evergreen/10 p-4 sm:p-5">
                                                                                                                                                                                                    <p className="text-sm text-muted">Total balance</p>
                                                                                                                                                                                                              <p className="mt-1 break-words font-heading text-xl font-semibold text-fg xl:text-2xl">
                                                                                                                                                                                                                          {money.format(summary.balance)}
                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                    <div className="min-w-0 rounded-xl border border-line bg-surface p-4 sm:p-5">
                                                                                                                                                                                                                                                              <p className="text-sm text-muted">Income in {monthLabel}</p>
                                                                                                                                                                                                                                                                        <p className="mt-1 break-words font-heading text-xl font-semibold text-evergreen xl:text-2xl">
                                                                                                                                                                                                                                                                                    {money.format(summary.monthIncome)}
                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                              <div className="min-w-0 rounded-xl border border-line bg-surface p-4 sm:p-5">
                                                                                                                                                                                                                                                                                                                        <p className="text-sm text-muted">Spending in {monthLabel}</p>
                                                                                                                                                                                                                                                                                                                                  <p className="mt-1 break-words font-heading text-xl font-semibold text-danger xl:text-2xl">
                                                                                                                                                                                                                                                                                                                                              {money.format(summary.monthExpense)}
                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                            <div className="mt-6 grid gap-6 xl:grid-cols-2">
                                                                                                                                                                                                                                                                                                                                                                                    <section className="min-w-0 rounded-xl border border-line bg-surface p-5">
                                                                                                                                                                                                                                                                                                                                                                                              <h2 className="font-heading text-lg font-semibold text-fg">
                                                                                                                                                                                                                                                                                                                                                                                                          Spending by category
                                                                                                                                                                                                                                                                                                                                                                                                                    </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="mb-4 text-sm text-muted">{monthLabel}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                        <SpendingByCategory data={summary.byCategory} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                        <section className="min-w-0 rounded-xl border border-line bg-surface p-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex items-center justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h2 className="font-heading text-lg font-semibold text-fg">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Recent transactions
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  href="/transactions"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="text-sm font-medium text-evergreen underline"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          View all
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {summary.recent.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="py-10 text-center text-sm text-muted">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    No transactions yet.{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Link href="/transactions" className="text-evergreen underline">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Add your first one.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <ul className="mt-4 divide-y divide-line">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {summary.recent.map((t) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <li
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  key={t.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="flex items-center justify-between gap-3 py-3"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="min-w-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="truncate text-sm font-medium text-fg">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {t.description || t.category}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-xs text-muted">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {t.category} &middot; {formatDate(t.date)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className={`shrink-0 text-sm font-semibold ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                t.type === "income" ? "text-evergreen" : "text-danger"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {t.type === "income" ? "+" : "-"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {money.format(t.amount)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }