"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

const inputClass =
  "mt-1 w-full rounded-lg border border-line bg-surface-2 px-3 py-2.5 text-fg outline-none placeholder:text-muted focus:border-evergreen focus:ring-2 focus:ring-evergreen/30";

  export default function AuthForm({ mode }: { mode: "sign-in" | "sign-up" }) {
    const router = useRouter();
      const [error, setError] = useState("");
        const [loading, setLoading] = useState(false);
          const isSignUp = mode === "sign-up";

            async function onSubmit(e: React.FormEvent<HTMLFormElement>) {
                e.preventDefault();
                    setError("");
                        setLoading(true);

                            const data = Object.fromEntries(new FormData(e.currentTarget));
                                const res = await fetch(
                                      isSignUp ? "/api/auth/register" : "/api/auth/login",
                                            {
                                                    method: "POST",
                                                            headers: { "Content-Type": "application/json" },
                                                                    body: JSON.stringify(data),
                                                                          }
                                                                              );
                                                                                  const json = await res.json().catch(() => ({}));
                                                                                      setLoading(false);

                                                                                          if (!res.ok) {
                                                                                                setError(json.error ?? "Something went wrong. Try again.");
                                                                                                      return;
                                                                                                          }
                                                                                                              router.push("/dashboard");
                                                                                                                  router.refresh();
                                                                                                                    }

                                                                                                                      return (
                                                                                                                          <form onSubmit={onSubmit} className="space-y-4">
                                                                                                                                {isSignUp && (
                                                                                                                                        <label className="block text-sm font-medium text-fg">
                                                                                                                                                  Full name
                                                                                                                                                            <input
                                                                                                                                                                        name="name"
                                                                                                                                                                                    type="text"
                                                                                                                                                                                                autoComplete="name"
                                                                                                                                                                                                            required
                                                                                                                                                                                                                        className={inputClass}
                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                          </label>
                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                      <label className="block text-sm font-medium text-fg">
                                                                                                                                                                                                                                                              Email address
                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                name="email"
                                                                                                                                                                                                                                                                                          type="email"
                                                                                                                                                                                                                                                                                                    autoComplete="email"
                                                                                                                                                                                                                                                                                                              required
                                                                                                                                                                                                                                                                                                                        className={inputClass}
                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                      </label>
                                                                                                                                                                                                                                                                                                                                            <label className="block text-sm font-medium text-fg">
                                                                                                                                                                                                                                                                                                                                                    Password
                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                      name="password"
                                                                                                                                                                                                                                                                                                                                                                                type="password"
                                                                                                                                                                                                                                                                                                                                                                                          autoComplete={isSignUp ? "new-password" : "current-password"}
                                                                                                                                                                                                                                                                                                                                                                                                    minLength={isSignUp ? 8 : undefined}
                                                                                                                                                                                                                                                                                                                                                                                                              required
                                                                                                                                                                                                                                                                                                                                                                                                                        className={inputClass}
                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                      </label>

                                                                                                                                                                                                                                                                                                                                                                                                                                            {error && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p role="alert" className="text-sm text-danger">
                                                                                                                                                                                                                                                                                                                                                                                                                                                              {error}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="w-full rounded-lg bg-evergreen px-4 py-2.5 font-semibold text-canvas transition hover:bg-mint disabled:opacity-60"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {loading ? "Please wait..." : isSignUp ? "Create account" : "Sign in"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }