"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "react-toastify";
import { Field } from "@/components/Field";

export default function DeleteAccount() {
  const router = useRouter();
    const [open, setOpen] = useState(false);
      const [busy, setBusy] = useState(false);

        async function onSubmit(e: React.FormEvent<HTMLFormElement>) {
            e.preventDefault();
                const password = String(new FormData(e.currentTarget).get("password") ?? "");
                    setBusy(true);

                        try {
                              const res = await fetch("/api/profile", {
                                      method: "DELETE",
                                              headers: { "Content-Type": "application/json" },
                                                      body: JSON.stringify({ password }),
                                                            });
                                                                  const json = await res.json().catch(() => ({}));

                                                                        if (!res.ok) {
                                                                                toast.error(json.error ?? "Could not delete your account.");
                                                                                        return;
                                                                                              }

                                                                                                    toast.success("Your account has been deleted.");
                                                                                                          router.push("/");
                                                                                                                router.refresh();
                                                                                                                    } catch {
                                                                                                                          toast.error("Network error. Check your connection and try again.");
                                                                                                                              } finally {
                                                                                                                                    setBusy(false);
                                                                                                                                        }
                                                                                                                                          }

                                                                                                                                            return (
                                                                                                                                                <>
                                                                                                                                                      <p className="text-sm text-muted">
                                                                                                                                                              Permanently delete your account and all of your transactions. This
                                                                                                                                                                      can&apos;t be undone.
                                                                                                                                                                            </p>
                                                                                                                                                                                  <button
                                                                                                                                                                                          type="button"
                                                                                                                                                                                                  onClick={() => setOpen(true)}
                                                                                                                                                                                                          className="mt-4 rounded-lg border border-danger/50 px-5 py-2.5 text-sm font-semibold text-danger transition hover:bg-danger/10"
                                                                                                                                                                                                                >
                                                                                                                                                                                                                        Delete account
                                                                                                                                                                                                                              </button>

                                                                                                                                                                                                                                    {open && (
                                                                                                                                                                                                                                            <div
                                                                                                                                                                                                                                                      role="dialog"
                                                                                                                                                                                                                                                                aria-modal="true"
                                                                                                                                                                                                                                                                          aria-labelledby="delete-title"
                                                                                                                                                                                                                                                                                    className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 sm:items-center sm:p-4"
                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                      <form
                                                                                                                                                                                                                                                                                                                  onSubmit={onSubmit}
                                                                                                                                                                                                                                                                                                                              className="w-full max-w-md rounded-t-2xl border border-line bg-surface p-5 sm:rounded-xl sm:p-6"
                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                    <h2
                                                                                                                                                                                                                                                                                                                                                                  id="delete-title"
                                                                                                                                                                                                                                                                                                                                                                                className="font-heading text-xl font-semibold text-fg"
                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                          Delete your account?
                                                                                                                                                                                                                                                                                                                                                                                                                      </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="mt-2 text-sm text-muted">
                                                                                                                                                                                                                                                                                                                                                                                                                                                All your transactions will be permanently removed. Enter your
                                                                                                                                                                                                                                                                                                                                                                                                                                                              password to confirm.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="mt-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Field
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    label="Password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    icon="lock"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    autoComplete="current-password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="mt-6 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={() => setOpen(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        disabled={busy}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="rounded-lg border border-line px-4 py-2.5 text-sm font-medium text-fg transition hover:border-evergreen disabled:opacity-60"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Cancel
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  disabled={busy}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="rounded-lg bg-danger px-4 py-2.5 text-sm font-semibold text-canvas transition hover:opacity-90 disabled:opacity-60"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {busy ? "Deleting..." : "Delete my account"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }