"use client";

import { useState } from "react";

const inputClass =
  "mt-1 w-full rounded-lg border border-line bg-surface-2 px-3 py-2.5 text-fg outline-none placeholder:text-muted focus:border-evergreen focus:ring-2 focus:ring-evergreen/30";

  export default function PasswordForm() {
    const [saving, setSaving] = useState(false);
      const [message, setMessage] = useState<{
          kind: "ok" | "error";
              text: string;
                } | null>(null);

                  async function onSubmit(e: React.FormEvent<HTMLFormElement>) {
                      e.preventDefault();
                          setMessage(null);

                              const form = e.currentTarget;
                                  const data = new FormData(form);
                                      const newPassword = String(data.get("newPassword") ?? "");
                                          const confirm = String(data.get("confirmPassword") ?? "");

                                              if (newPassword !== confirm) {
                                                    setMessage({ kind: "error", text: "The new passwords don't match." });
                                                          return;
                                                              }

                                                                  setSaving(true);
                                                                      const res = await fetch("/api/profile/password", {
                                                                            method: "PUT",
                                                                                  headers: { "Content-Type": "application/json" },
                                                                                        body: JSON.stringify({
                                                                                                currentPassword: data.get("currentPassword"),
                                                                                                        newPassword,
                                                                                                              }),
                                                                                                                  });
                                                                                                                      const json = await res.json().catch(() => ({}));
                                                                                                                          setSaving(false);

                                                                                                                              if (!res.ok) {
                                                                                                                                    setMessage({ kind: "error", text: json.error ?? "Could not update." });
                                                                                                                                          return;
                                                                                                                                              }
                                                                                                                                                  form.reset();
                                                                                                                                                      setMessage({ kind: "ok", text: "Password updated." });
                                                                                                                                                        }

                                                                                                                                                          return (
                                                                                                                                                              <form onSubmit={onSubmit} className="space-y-4">
                                                                                                                                                                    <label className="block text-sm font-medium text-fg">
                                                                                                                                                                            Current password
                                                                                                                                                                                    <input
                                                                                                                                                                                              name="currentPassword"
                                                                                                                                                                                                        type="password"
                                                                                                                                                                                                                  autoComplete="current-password"
                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                      className={inputClass}
                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                    </label>
                                                                                                                                                                                                                                                          <label className="block text-sm font-medium text-fg">
                                                                                                                                                                                                                                                                  New password
                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                    name="newPassword"
                                                                                                                                                                                                                                                                                              type="password"
                                                                                                                                                                                                                                                                                                        autoComplete="new-password"
                                                                                                                                                                                                                                                                                                                  minLength={8}
                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                      className={inputClass}
                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                    </label>
                                                                                                                                                                                                                                                                                                                                                          <label className="block text-sm font-medium text-fg">
                                                                                                                                                                                                                                                                                                                                                                  Confirm new password
                                                                                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                                                                                    name="confirmPassword"
                                                                                                                                                                                                                                                                                                                                                                                              type="password"
                                                                                                                                                                                                                                                                                                                                                                                                        autoComplete="new-password"
                                                                                                                                                                                                                                                                                                                                                                                                                  minLength={8}
                                                                                                                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                                                                                                                      className={inputClass}
                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                          {message && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            role={message.kind === "error" ? "alert" : "status"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className={`text-sm ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  message.kind === "error" ? "text-danger" : "text-evergreen"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {message.text}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  disabled={saving}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="rounded-lg bg-evergreen px-5 py-2.5 text-sm font-semibold text-canvas transition hover:bg-mint disabled:opacity-60"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {saving ? "Updating..." : "Update password"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }