"use client";

import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from "recharts";
import { money } from "@/lib/format";

const COLORS = [
  "#10B981",
    "#0EA5A4",
      "#6EE7B7",
        "#334155",
          "#0B1220",
            "#94A3B8",
              "#34D399",
                "#CBD5E1",
                ];

                export default function SpendingByCategory({
                  data,
                  }: {
                    data: { category: string; total: number }[];
                    }) {
                      const total = data.reduce((sum, d) => sum + d.total, 0);

                        if (data.length === 0) {
                            return (
                                  <p className="py-10 text-center text-sm">
                                          No spending recorded this month yet.
                                                </p>
                                                    );
                                                      }

                                                        return (
                                                            <div className="flex flex-col items-center gap-6 sm:flex-row">
                                                                  <div className="relative h-52 w-52 shrink-0">
                                                                          <ResponsiveContainer width="100%" height="100%">
                                                                                    <PieChart>
                                                                                                <Pie
                                                                                                              data={data}
                                                                                                                            dataKey="total"
                                                                                                                                          nameKey="category"
                                                                                                                                                        innerRadius={62}
                                                                                                                                                                      outerRadius={90}
                                                                                                                                                                                    paddingAngle={2}
                                                                                                                                                                                                  stroke="none"
                                                                                                                                                                                                              >
                                                                                                                                                                                                                            {data.map((_, i) => (
                                                                                                                                                                                                                                            <Cell key={i} fill={COLORS[i % COLORS.length]} />
                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                      </Pie>
                                                                                                                                                                                                                                                                                  <Tooltip formatter={(value) => money.format(Number(value))} />
                                                                                                                                                                                                                                                                                            </PieChart>
                                                                                                                                                                                                                                                                                                    </ResponsiveContainer>
                                                                                                                                                                                                                                                                                                            <div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center">
                                                                                                                                                                                                                                                                                                                      <span className="text-xs">Total spent</span>
                                                                                                                                                                                                                                                                                                                                <span className="text-sm font-semibold text-midnight">
                                                                                                                                                                                                                                                                                                                                            {money.format(total)}
                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                          <ul className="w-full space-y-2 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                  {data.map((d, i) => (
                                                                                                                                                                                                                                                                                                                                                                                            <li key={d.category} className="flex items-center justify-between gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                        <span className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                      <span
                                                                                                                                                                                                                                                                                                                                                                                                                                      className="h-2.5 w-2.5 rounded-full"
                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{ background: COLORS[i % COLORS.length] }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {d.category}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="font-medium text-midnight">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {Math.round((d.total / total) * 100)}%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }