"use client";

import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from "recharts";
import { money } from "@/lib/format";

const COLORS = [
  "#10B981",
    "#38BDF8",
      "#FBBF24",
        "#A78BFA",
          "#34D399",
            "#F472B6",
              "#0EA5A4",
                "#94A3B8",
                ];

                export default function SpendingByCategory({
                  data,
                  }: {
                    data: { category: string; total: number }[];
                    }) {
                      const total = data.reduce((sum, d) => sum + d.total, 0);

                        if (data.length === 0) {
                            return (
                                  <p className="py-10 text-center text-sm text-muted">
                                          No spending recorded this month yet.
                                                </p>
                                                    );
                                                      }

                                                        return (
                                                            <div className="flex flex-col items-center gap-6 sm:flex-row">
                                                                  <div className="relative h-52 w-52 shrink-0">
                                                                          <ResponsiveContainer width="100%" height="100%">
                                                                                    <PieChart>
                                                                                                <Pie
                                                                                                              data={data}
                                                                                                                            dataKey="total"
                                                                                                                                          nameKey="category"
                                                                                                                                                        innerRadius={62}
                                                                                                                                                                      outerRadius={90}
                                                                                                                                                                                    paddingAngle={2}
                                                                                                                                                                                                  stroke="none"
                                                                                                                                                                                                              >
                                                                                                                                                                                                                            {data.map((_, i) => (
                                                                                                                                                                                                                                            <Cell key={i} fill={COLORS[i % COLORS.length]} />
                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                      </Pie>
                                                                                                                                                                                                                                                                                  <Tooltip
                                                                                                                                                                                                                                                                                                formatter={(value) => money.format(Number(value))}
                                                                                                                                                                                                                                                                                                              contentStyle={{
                                                                                                                                                                                                                                                                                                                              background: "#182339",
                                                                                                                                                                                                                                                                                                                                              border: "1px solid #243247",
                                                                                                                                                                                                                                                                                                                                                              borderRadius: 8,
                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                          itemStyle={{ color: "#F1F5F9" }}
                                                                                                                                                                                                                                                                                                                                                                                                        labelStyle={{ color: "#F1F5F9" }}
                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                              </PieChart>
                                                                                                                                                                                                                                                                                                                                                                                                                                      </ResponsiveContainer>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="text-xs text-muted">Total spent</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-sm font-semibold text-fg">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {money.format(total)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <ul className="w-full space-y-2 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {data.map((d, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <li
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          key={d.category}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="flex items-center justify-between gap-3"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="flex items-center gap-2 text-muted">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="h-2.5 w-2.5 rounded-full"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={{ background: COLORS[i % COLORS.length] }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {d.category}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="font-medium text-fg">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {Math.round((d.total / total) * 100)}%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }